### ISSUE TITLE
Read &| Write ?

### ISSUE THREAD

**Issue by k0pernicus** [jangko/nimpdf#15]
First, awesome work! :-)
I am trying to parse PDF files in order to retrieve information from them, like font style, font family, text, etc...
I am wondering if your library is just for writing PDF file, or if this one is able to read and parse an existing PDF file?
If yes, have you some examples please?

Thanks a lot!

**Comment by jangko** [comment]
I am sorry, nimPDF only write PDF file, cannot parse at all.
