### ISSUE TITLE
How do I use a Japanese vertical writing font?

### ISSUE THREAD

**Issue by suihakei** [jangko/nimpdf#36]
I would use the `drawVText` function when using vertical writing.
In fact, I was able to use `drawVText` to output vertical writing.
However, some Japanese words were not written vertically.

For example, numbers.
The following image is correct for vertical writing of numbers in Japanese.
![image](https://user-images.githubusercontent.com/17183033/125238386-212e2e80-e322-11eb-9c89-7d6f7e566e18.png)

However, the vertical numbers output by nimPDF will look like the image below.
![image](https://user-images.githubusercontent.com/17183033/125238527-5044a000-e322-11eb-9872-5764a2a21b02.png)

There are other symbols.
A colon with vertical writing output in NimPDF looks like this:
![image](https://user-images.githubusercontent.com/17183033/125238683-8550f280-e322-11eb-92c5-0605afba79c2.png)
The correct vertical writing style for Japanese is shown in the figure below.
![image](https://user-images.githubusercontent.com/17183033/125238851-d06b0580-e322-11eb-848b-87dca287a7a1.png)

How can I do this kind of vertical writing of Japanese in nimPDF?
I would appreciate it if you could let me know.
Thank you very much.

**Comment by jangko** [comment]
Vertical text style need the vertical text information from the font. If the font does not support vertical text style, nimPDF will fallback to default style regardless of the text language.

Work around for your situation is using text rotation. you can find the sample in demo/demo.nim, then search for rotating text in page 7 of that demo.

**Comment by suihakei** [comment]
Thank you for your reply.

> Vertical text style need the vertical text information from the font
I don't know much about Font files, but for example, if I specify a Font that can be used for vertical writing in Photo shop, etc., it will be misaligned in nimPDF.
Doesn't this mean that I have to rotate it?

**PhotoShop**
![](https://user-images.githubusercontent.com/17183033/125238386-212e2e80-e322-11eb-9c89-7d6f7e566e18.png)

**nimPDF**
![](https://user-images.githubusercontent.com/17183033/125238527-5044a000-e322-11eb-9872-5764a2a21b02.png)

**Comment by jangko** [comment]
> Doesn't this mean that I have to rotate it?

yes, nimPDF currently does not support mixed text orientation. you have to use rotation.

**Comment by suihakei** [comment]
Thank you for your reply.

> you have to use rotation.

I understand!
I'll try it!
Thank you!
