### ISSUE TITLE
Embedded TTF fonts are not available for re-procesessing

### ISSUE THREAD

**Issue by ThomasTJdev** [jangko/nimpdf#39]
* When using TTF fonts, e.g. Roboto, these will get embedded, but they are not available for re-procesessing.
* I need to use some special characters, æøå, and I would like to use ghostscript (gs) to compress the file afterwards. But procesessing the file with gs renders the text without a font making it impossible to copy/paste from the document afterwards.

## Test
By running the command below on the `demo/test.pdf` gs creates a file, but as shown in the output there are problems with the CMap. This file will not allow the user to copy/paste from it ([testgs.pdf](https://github.com/jangko/nimpdf/files/7586783/testgs.pdf)).
```shell
$ gs -sDEVICE=pdfwrite -dBATCH -sOutputFile=demo/testgs.pdf demo/test.pdf
GPL Ghostscript 9.55.0 (2021-09-27)
Copyright (C) 2021 Artifex Software, Inc.  All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.
Processing pages 1 through 1.
Page 1
Loading NimbusSans-Bold font from /usr/share/ghostscript/9.55.0/Resource/Font/NimbusSans-Bold... 5066780 3552663 2454032 1075490 4 done.
   **** Warning: Failed to read ToUnicode CMap.
   **** Warning: Failed to read ToUnicode CMap.
   **** Warning: Failed to read ToUnicode CMap
```
## PDF data
The demo file `demo/test.pdf` uses multiple fonts which seems to be embedded correct but with some errors in the CMap:
```shell
$ pdffonts test.pdf
Syntax Warning: Illegal entry in bfchar block in ToUnicode CMap
Syntax Warning: Illegal entry in bfchar block in ToUnicode CMap
Syntax Warning: Illegal entry in bfchar block in ToUnicode CMap
Syntax Warning: Illegal entry in bfchar block in ToUnicode CMap
Syntax Warning: Illegal entry in bfchar block in ToUnicode CMap
Syntax Warning: Illegal entry in bfchar block in ToUnicode CMap
Syntax Warning: Illegal entry in bfchar block in ToUnicode CMap
Syntax Warning: Illegal entry in bfchar block in ToUnicode CMap
Syntax Warning: Illegal entry in bfchar block in ToUnicode CMap
Syntax Warning: Illegal entry in bfchar block in ToUnicode CMap
Syntax Warning: Illegal entry in bfchar block in ToUnicode CMap
Syntax Warning: Illegal entry in bfchar block in ToUnicode CMap
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
NIMPDI+Calligrapher Regular          CID TrueType      Identity-H       yes yes yes     24  0
NIMPDG+Eunjin                        CID TrueType      Identity-H       yes yes yes     10  0
Helvetica-Bold                       Type 1            Standard         no  no  no       3  0
NIMPDH+KaiTi                         CID TrueType      Identity-H       yes yes yes     17  0
```

Running the file through an online check produces this font result:
```
Fonts Results
    Errors:
        Uses Base 14 fonts not embedded in document:
            Helvetica-Bold (1 instance)
    Information:
        Uses fonts that do not allow text to be extracted:
            Helvetica-Bold, SubType: Type1 (1 instance)
            NIMPDG+Eunjin, SubType: Type0 (1 instance)
            NIMPDH+KaiTi, SubType: Type0 (1 instance)
            NIMPDI+Calligrapher Regular, SubType: Type0 (1 instance)
    Checks Completed:
        fontdescriptor-missing-capheight
        fontdescriptor-missing-fields
        found-non-extractible-text
        uses-base14fonts-not-embedded
        uses-fonts-fully-embedded
        uses-fonts-not-embedded
```

When extracting the font from the PDF file and reviewing it in FontForge the unknown characters are shown with unknown mapping `?`. If I use Roboto or other fonts, some of the characters (default) will be mapped correct, but all special characters will be shown under `?` and that will ruin the whole procesessing.
![image](https://user-images.githubusercontent.com/1888696/142996257-26e37906-85c0-4333-8163-5fe457ed2332.png)

**Comment by jangko** [comment]
> these will get embedded, but they are not available for re-procesessing.

this is not a bug, but a feature. nimPDF only embed a _subset_ of used characters from a font file, not embed  entire file. and during that process, the codepoint to glyph will also remapped to create a smaller cmap. all other `tables` not used for rendering font in a PDF will be discarded.

because of how the fonts are embeded in nimPDF, the error messages you see are expected. the embedded cmap only works for PDF renderer, not to be reprocessed by other font tools.

**Comment by ThomasTJdev** [comment]
Oh, I see - thank you for the explanation! I will find another way for pre-procesessing my image files.
