### ISSUE TITLE
How to properly output Cyrrilic chars encoded in UTF-8?

### ISSUE THREAD

**Issue by x86128** [jangko/nimpdf#9]
Hi! 
I'm trying to "Hello, world" PDF with some cyrrilic chars with this simple code:
```
import streams, "source/nimpdf"

var fo = newFileStream("book.pdf", fmWrite)

var doc = initPDF()
let pSize = getSizeFromName("A4")

doc.addPage(pSize, PGO_PORTRAIT)
doc.setFont("monospace", {FS_REGULAR}, 5'f64, ENC_UTF8)

doc.drawText(15, 15, "Обычный текст в кодировке UTF-8")

doc.writePDF(fo)
close(fo)
```
After hours of time, it's builds against 0.15.3 and outputs pdf, but without any cyrrilic char.
I'd changed ENC_STD -> ENC_UTF8, diffrent font families and so, but nothing helps.

**Comment by jangko** [comment]
I know it's frustrating sometime working with library without proper documentation.

nimPDF will looking for the requested font by their internal name+style, not the filename.
Make sure the font file contains the needed glyphs,  in this case the Cyrilic glyphs.
I use Arial Unicode MS font as an example, but of course you can use  any other fonts that support Cyrilic glyphs.

```nimrod
import streams, "source/nimpdf"

var fo = newFileStream("book.pdf", fmWrite)

var opts = makeDocOpt()
# use apropriate OS specific API to obtain fonts folder
# or supply your own fonts folder
opts.addFontsPath("C:\\Windows\\Fonts") 

var doc = initPDF(opts)
let pSize = getSizeFromName("A4")

doc.addPage(pSize, PGO_PORTRAIT)

doc.setFont("Arial Unicode MS", {FS_REGULAR}, 5'f64, ENC_UTF8)

doc.drawText(15, 15, "Обычный текст в кодировке UTF-8")

doc.writePDF(fo)
close(fo)
```

**Comment by x86128** [comment]
Thnx for reply!
I've changed code like this:
```nim
import streams, "source/nimpdf"

var fo = newFileStream("book.pdf", fmWrite)

var opts = makeDocOpt()
opts.addFontsPath("/usr/share/fonts/truetype/freefont/")

var doc = initPDF(opts)

let pSize = getSizeFromName("A4")

doc.addPage(pSize, PGO_PORTRAIT)

doc.setFont("FreeMono", {FS_REGULAR}, 5'f64, ENC_UTF8)

doc.drawText(15, 15, "Обычный текст в кодировке UTF-8")

doc.writePDF(fo)
close(fo)
```
and programm just hangs at 100% cpu usage.
After ctrl-c break:
```
^CTraceback (most recent call last)
pdfer.nim(16)            pdfer
nimpdf.nim(622)          drawText
fontmanager.nim(109)     EscapeString
fontmanager.nim(119)     EscapeString
CMAPTable.nim(81)        GlyphIndex
CMAPTable.nim(285)       GlyphIndex
CMAPTable.nim(273)       StartCode
FontData.nim(289)        ReadULongAsInt
FontData.nim(283)        ReadULong
SIGINT: Interrupted by Ctrl-C.
```

**Comment by jangko** [comment]
can you please send the suspected font file via something like DropBox or provide a link where i can download it? I think the font parser has some problem with the FreeMono font.

**Comment by x86128** [comment]
I'm using Nim 0.15.3 builded on Ubuntu 16.04 LTS.
FreeMono.ttf from standard system packet.
[https://drive.google.com/open?id=0BzpJvdNcTnRYOXdyRWJtX1QtZjg](https://drive.google.com/open?id=0BzpJvdNcTnRYOXdyRWJtX1QtZjg)
Can you explain in "two words" how PDF-format internally keeps text: with codes of glyphs in font file or font-aware with codes of Unicode char?

**Comment by jangko** [comment]
PDF format  knows nothing of unicode actually, what PDF format knows is index(position) of glyphs in font file. It's up to the app/library designer to implement unicode aware library/application.
Font file will go through subsetting process(removing not needed glyphs) and then embed the subset in the final PDF file.
Thanks for the link you've provided, I will analyze it.

**Comment by x86128** [comment]
Is any "standard" font that **not needed** to be embeded in resulting PDF file?

**Comment by jangko** [comment]
PDF standard font, 14 of them, only support Latin-1 script, no Cyrillic glyphs.
Please try the newest commit, I already fixed FreeMono problem.

**Comment by x86128** [comment]
Ok. It works perfect.
But I've patched some sources to successfully build on Linux with case sensitive file system. #10
